Fix for wrong order of arguments in function calls in `_click()`
Fix for wrong order of arguments in function calls in `_click()`, which results in exception:

      File "/usr/local/lib/python3.4/dist-packages/Xlib/protocol/rq.py", line 1459, in __init__
        self._binary = self._request.to_binary(*args, **keys)
      File "<string>", line 2, in to_binary
    struct.error: ubyte format requires 0 <= number <= 255

`button` is passed as `x` coordinate and `y` coordinate is passed as `button`. Thus, raising exception because button has larger value than 255 most of the time.